server:
  port: 8082

spring:
  application:
    name: mock-bank
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
