-- V3: payments, refunds, idempotency keys, and three demo merchants.

-- ---------------------------------------------------------------------------
-- Payments
-- ---------------------------------------------------------------------------
CREATE TABLE payments (
    id                UUID        PRIMARY KEY, -- generated by the app, so it can be sent to the bank first
    merchant_id       BIGINT      NOT NULL REFERENCES merchants (id),
    amount            BIGINT      NOT NULL CHECK (amount > 0),
    currency          TEXT        NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    card_token        TEXT        NOT NULL,
    merchant_order_id TEXT        NOT NULL,
    status            TEXT        NOT NULL CHECK (status IN ('PENDING', 'CAPTURED', 'FAILED', 'UNKNOWN')),
    refunded_amount   BIGINT      NOT NULL DEFAULT 0,
    decline_reason    TEXT,
    bank_reference    TEXT,
    idempotency_key   TEXT        NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    version           BIGINT      NOT NULL DEFAULT 0,
    CHECK (refunded_amount BETWEEN 0 AND amount),          -- can't refund more than was paid
    CHECK (refunded_amount = 0 OR status = 'CAPTURED'),    -- only captured money can be refunded
    UNIQUE (merchant_id, idempotency_key)                  -- one payment per idempotency key
);

-- Listing: GET /v1/payments, keyset-paginated on (created_at, id), newest first.
CREATE INDEX payments_merchant_created_idx ON payments (merchant_id, created_at DESC, id DESC);

-- Reconciler: only unresolved payments, so the index stays tiny however many payments exist.
CREATE INDEX payments_unresolved_idx ON payments (updated_at) WHERE status IN ('PENDING', 'UNKNOWN');

-- Status can only move forward: PENDING -> CAPTURED | FAILED | UNKNOWN, UNKNOWN -> CAPTURED | FAILED.
CREATE FUNCTION payments_check_status_transition() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.status = OLD.status
       OR (OLD.status = 'PENDING' AND NEW.status IN ('CAPTURED', 'FAILED', 'UNKNOWN'))
       OR (OLD.status = 'UNKNOWN' AND NEW.status IN ('CAPTURED', 'FAILED')) THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'payment %: illegal status transition % -> %', OLD.id, OLD.status, NEW.status
        USING ERRCODE = 'check_violation';
END;
$$;

CREATE TRIGGER payments_status_transition
    BEFORE UPDATE OF status ON payments
    FOR EACH ROW EXECUTE FUNCTION payments_check_status_transition();

-- The FK promised in V2: every journal entry belongs to a real payment.
ALTER TABLE journal_entries
    ADD CONSTRAINT journal_entries_payment_id_fk FOREIGN KEY (payment_id) REFERENCES payments (id);

-- ---------------------------------------------------------------------------
-- Refunds (the money movement itself is a REFUND journal entry)
-- ---------------------------------------------------------------------------
CREATE TABLE refunds (
    id          UUID        PRIMARY KEY,
    payment_id  UUID        NOT NULL REFERENCES payments (id),
    merchant_id BIGINT      NOT NULL REFERENCES merchants (id),
    amount      BIGINT      NOT NULL CHECK (amount > 0),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX refunds_payment_id_idx ON refunds (payment_id);

-- ---------------------------------------------------------------------------
-- Idempotency keys
-- IN_PROGRESS rows are a lock held until locked_until; COMPLETED rows hold the response to replay.
-- ---------------------------------------------------------------------------
CREATE TABLE idempotency_keys (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    merchant_id   BIGINT      NOT NULL REFERENCES merchants (id),
    key           TEXT        NOT NULL CHECK (length(key) BETWEEN 1 AND 255),
    request_hash  TEXT        NOT NULL,
    status        TEXT        NOT NULL CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    response_code INT,
    response_body JSONB,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_until  TIMESTAMPTZ NOT NULL,
    CHECK ((status = 'COMPLETED') = (response_code IS NOT NULL AND response_body IS NOT NULL)),
    UNIQUE (merchant_id, key)
);

-- ---------------------------------------------------------------------------
-- Demo merchants. Only SHA-256 hashes of the API keys are stored; the raw keys are in README.md.
-- ---------------------------------------------------------------------------
INSERT INTO merchants (name, api_key_hash, webhook_url, webhook_secret, rate_limit_tier) VALUES
    ('Chai Point',   '6474ca4bfd9754170b61d78c24e94c24af28d55e3ae22acd6d1e597ee8f8852d',
     'http://localhost:8083/webhooks', 'whsec_demo_chaipoint',   'STANDARD'),
    ('Book Nook',    '470e20ee42715ac24ebb80b732c3c9faf5f7da58a642f4a08f43203710f3d07b',
     'http://localhost:8083/webhooks', 'whsec_demo_booknook',    'FREE'),
    ('Pixel Prints', 'e01532823627abe4e1f4b9d4a063377d99fa1e969ab95624d237f94dba5c0772',
     'http://localhost:8083/webhooks', 'whsec_demo_pixelprints', 'PREMIUM');

INSERT INTO accounts (owner_type, owner_id, type, currency)
SELECT 'MERCHANT', id, 'MERCHANT_PAYABLE', 'INR' FROM merchants
WHERE name IN ('Chai Point', 'Book Nook', 'Pixel Prints');
